name: Deploy React App to Azure

on:
  push:
    branches:
      - main  # Trigger the deployment on push to the 'main' branch (you can change this if needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CodeQL
      uses: github/codeql-action/setup@v3  # Set up CodeQL Action

    - name: Initialize CodeQL
      uses: github/codeql-action/autobuild@v3  # Automatically detect and build your project

    - name: Run CodeQL analysis
      uses: github/codeql-action/analyze@v3  # Run the actual static analysis

    - name: Upload CodeQL results
      uses: github/codeql-action/upload-results@v3  # Upload the results of the analysis for review


    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use the Node.js version you prefer (React works well with Node.js 16)

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build the React app
    - name: Build the React app
      run: npm run build

    # Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Mintyapp'  # Replace with your Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './build'
